language: node_js
node_js:
- 8.9.4
after_success:
- ssh root@192.168.137.130 "cd ~/travis_test && git pull && pm2 restart pm2.json --name
  test_server"
before_install:
- openssl aes-256-cbc -K $encrypted_1246a5cf2bec_key -iv $encrypted_1246a5cf2bec_iv
  -in github_rsa.enc -out ~/.ssh/github_rsa -d
